[package]
name = "nispor-cli"
version = "0.3.0"
authors = ["Gris Ge <cnfourt@gmail.com>"]
edition = "2018"

[[bin]]
name = "npc"
path = "npc.rs"

[dependencies]
serde_json = "1.0"
nispor = { path = "../lib" }
