[package]
name = "nispor-cli"
version = "1.0.1"
authors = ["Gris Ge <cnfourt@gmail.com>"]
edition = "2018"

[[bin]]
name = "npc"
path = "npc.rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
clap = "2.33.3"
nispor = { path = "../lib" }
serde_yaml = "0.8"
